version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: DB.Dockerfile
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  node-app:
    build:
      context: .
      dockerfile: App.Dockerfile
    container_name: node_app
    image: nodeapp
    ports:
      - 3000:3000
    volumes:
      - ./:/node/dp-my-chat
    links:
      - mongodb:db
      - minio:minio
    env_file: ./config/.env
  minio:
    image: "minio/minio"
    command: server /export
    restart: always
    environment:
      MINIO_ACCESS_KEY: KBP6WXGPS387090EZMG8
      MINIO_SECRET_KEY: DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A
    ports:
      - "9000:9000"
    volumes:
      - ./.minio-data:/export
# run by "docker-compose up --build -d"